- name: install bazel
  hosts: all
  tasks:
  - become: "yes"
    get_url:
      dest: /usr/local/bin/bazel
      mode: "0755"
      url: >-
        https://github.com/bazelbuild/bazel/releases/download/3.7.2/bazel-3.7.2-linux-x86_64
    name: install bazel
